[project]
name = "model-monitoring-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Makarand", email = "makarand.ghule@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
model-monitoring-agent = "model_monitoring_agent:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
